### PR TITLE
Delete Template from DockingManager style.

### PR DESCRIPTION
**Pull request by Kibnet**
Fix error then try resize autohide panel in Gemini.

### CODE REVIEW

**Comment by 4ux-nbIx** [comment]
Hi Kibnet,
Could you please explain why did you need remove the template and what problem you are trying to fix?

Thanks!

**Comment by Kibnet** [comment]
Of course!
If you use this style together with GeminiWpf framework, you get error caused crash of the whole application. This occurs when you try to resize the panel, which was set to autohide mode. Removed template repeats exactly the parent and not semantic meaning. But it causes the above error.

**Comment by 4ux-nbIx** [comment]
Ok, sounds reasonable, thanks! I'll merge your pull request now...

**Comment by Kibnet** [comment]
Thank you!

**Comment by 4ux-nbIx** [comment]
I've also updated NuGet package. Should be available soon...

**Pull request merged**
